version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn install -DskipTests
  build:
    commands:
      - echo Building the application...
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/*.jar
